import java.util.ArrayList;
import java.util.Scanner;

public class RunNeuralNetwork
{
    //features
    private static Scanner userScanner = new Scanner ( System.in );
    private static NeuralNetwork neuralNetwork = new NeuralNetwork ( );
    
    
    public static void main ( String [ ] stuff )
    {
        doTraining ( );
        runMainMenu ( );
    }
    
    
    //test neural network
    public static void runMainMenu ( )
    {
        System.out.println ( "Universal Ai Diploma Neural Network, January 28, 2022" );
        System.out.println ( "1. Get neural network guess answer for input [0,0]" );
        System.out.println ( "2. Get neural network guess answer for input [0,1]" );
        System.out.println ( "3. Get neural network guess answer for input [1,0]" );
        System.out.println ( "4. Get neural network guess answer for input [1,1]" );
        System.out.println ( "5. Exit!" );
        System.out.println ( "Select an option" );
        
        int userOption = userScanner.nextInt ( );
        switch ( userOption )
        {
            case 1:
            {
                int [ ] inputs = new int [ ] { 0, 0 };
                neuralNetwork.doForwardPropagation ( inputs );
                double neuralNetworkAnswer = neuralNetwork.getOutcome ( );
                System.out.println ( "Neural network guess for input [0,0] >> " + neuralNetworkAnswer );
                returnToMainMenu ( );
            } 
            break;
            
            case 2:
            {
                int [ ] inputs = new int [ ] { 0, 1 };
                neuralNetwork.doForwardPropagation ( inputs );
                double neuralNetworkAnswer = neuralNetwork.getOutcome ( );
                System.out.println ( "Neural network guess for input [0,1] >> " + neuralNetworkAnswer );
                returnToMainMenu ( );
            } 
            break;
            
            
            case 3:
            {
                int [ ] inputs = new int [ ] { 1, 0 };
                neuralNetwork.doForwardPropagation ( inputs );
                double neuralNetworkAnswer = neuralNetwork.getOutcome ( );
                System.out.println ( "Neural network guess for input [1,0] >> " + neuralNetworkAnswer );
                returnToMainMenu ( );
            } 
            break;
            
            
            case 4:
            {
                int [ ] inputs = new int [ ] { 1, 1 };
                neuralNetwork.doForwardPropagation ( inputs );
                double neuralNetworkAnswer = neuralNetwork.getOutcome ( );
                System.out.println ( "Neural network guess for input [1,1] >> " + neuralNetworkAnswer );
                returnToMainMenu ( );
            } 
            break;
            
            
            case 5:
            {
                System.exit ( 0 );
            } 
            break; 
        }
    }
    
    public static void returnToMainMenu ( )
    {
        userScanner.nextLine ( );
        userScanner.nextLine ( );
        runMainMenu ( );
    }
    
    
    public static void doTraining ( )
    {
        ArrayList <String> trainingData = getTrainingData ( );
        
        for ( int tDI = 0; tDI < trainingData.size ( ); tDI ++ )
        {
           //forward propagation   
           String [ ] eachTrainingLine = trainingData.get ( tDI ).split ( "::" );
           int inputPartA = Integer.parseInt ( eachTrainingLine [ 0 ].split ( "," ) [ 0 ] );
           int inputPartB = Integer.parseInt ( eachTrainingLine [ 0 ].split ( "," ) [ 1 ]  );
           int [ ] trainingInputs = new int [ ] { inputPartA, inputPartB };
           neuralNetwork.doForwardPropagation ( trainingInputs );
           
           //backward propagation
           int eachTrainingTarget = Integer.parseInt ( trainingData.get ( tDI ).split ( "::" ) [ 1 ] );
           neuralNetwork.doBackwardPropagation ( eachTrainingTarget );
        }
    }
    
    
    public static ArrayList <String> getTrainingData ( )
    {
        ArrayList <String> returnValue = new ArrayList <String> ( );
        
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        
        return returnValue;
    }
}